apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: getaddrip-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "getaddr.carlo.ltd"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: getaddrip
spec:
  hosts:
  - "getaddr.carlo.ltd"
  gateways:
  - getaddrip-gateway
  http:
    route:
    - destination:
        host: getaddrip
        port:
          number: 80
