apiVersion: v1
kind: Service
metadata:
  name: getaddrip
  labels:
    app: getaddrip
spec:
  ports:
  - port: 7777
    name: http
  selector:
    app: getaddrip
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: getaddrip-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: getaddrip
        version: v1
    spec:
      containers:
      - name: getaddrip
        image: carlo/getaddrip:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
